// This class is automatically included in FastlaneRunner during build

// This autogenerated file will be overwritten or replaced during build time, or when you initialize `scan`
class Scanfile: ScanfileProtocol {

    var workspace: String? { return "FastlaneSwiftDemo" }
    var scheme: String? { return "FastlaneSwiftDemo" }
    var codeCoverage: Bool? { return true }
    var addressSanitizer: Bool? { return true }
    var outputDirectory: String { return "./reports" }
    var outputTypes: String { return "html,junit" }
    var buildlogPath: String { return "~/Library/Logs/scan" }
    
}





// Generated with fastlane 2.70.1
